"use client"; // Ensure this is at the top of the file

// import { Inter } from "next/font/google";
import { CartProvider } from "./context/CartContext";
import Link from "next/link";
import "./globals.css";
import { ToastContainer } from "react-toastify";

// const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-gray-50 text-gray-900">
        <CartProvider>
          <header className="bg-white shadow-md">
            <div className="container mx-auto flex items-center justify-between p-4">
              {/* Logo */}
              <div className="flex items-center space-x-3">
                <img
                  src="/Zomato_logo.png"
                  alt="Restaurant Logo"
                  className="h-10 w-10"
                />
                <span className="text-xl font-bold">Zomato</span>
              </div>
              {/* Navigation */}
              <nav className="space-x-6">
                <Link href="/" className="text-gray-700 hover:text-gray-900">
                  Home
                </Link>
                <Link
                  href="/menu"
                  className="text-gray-700 hover:text-gray-900"
                >
                  Menu
                </Link>
                <Link
                  href="/cart"
                  className="text-gray-700 hover:text-gray-900"
                >
                  Cart
                </Link>
              </nav>
            </div>
          </header>

          {/* Main Content */}
          <main className="mx-auto ">{children}</main>

          <footer className="absolute bottom-0 bg-white shadow-md mt-12 p-4 w-full">
            <div className="container mx-auto text-center text-gray-600">
              &copy; 2024 Zomato. All rights reserved.
            </div>
          </footer>
          <ToastContainer />

        </CartProvider>
      </body>
    </html>
  );
}
